#!/bin/bash

DAILY_REGRESSION_TEST_COMMANDS="[
    {
        'name':'RocksDB daily regression test',
        'oncall':'rocksdb_point_of_contact',
        'steps': [
            {
                'name':'Request or update the certificate for root',
                'shell':'mkdir -p .ssh && /usr/bin/rolecertreq --verbose --debug --use-dir .ssh',
                'user':'root',
            },
            {
                'name':'Verify SSH access',
                'shell':'/usr/bin/ssh -i .ssh/id_rsa root@udb4470.prn1.facebook.com ls',
                'user':'root',
            },
            {
                'name':'Fetch tools',
                'shell':'fbpkg fetch rocksdb.regression_test_tools',
                'user':'root',
            },
            {
                'name':'Run RocksDB regression test script',
                'timeout':86400,
                'shell':'REMOTE_HOST=udb4470.prn1.facebook.com REPORTER=./report_rocksdb_bench_result MAILER=./email_notification.par OPTIONS_DIR=fbcode/fbcode/rocks/tools/regression_test_options fbcode/fbcode/rocks/tools/rocks_regression_test.sh',
                'user':'root',
            },
        ],
    }
]"

echo $DAILY_REGRESSION_TEST_COMMANDS
